apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec: 
  workspaces:
    - name: source
  steps:
    - name: npminstall
      image: node:20-buster-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        echo "***** Environment *****"
        npm --version
        pwd
        echo "***** Cleaning npm cache *****"
        npm cache clean --force
         echo "***** Running npm install *****"
         npm install
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata: 
  name: jasmine
spec:
  workplaces:
    - name: source
  steps:
    - name: jasminetests
      images; node:20-buster-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        echo "***** Running jasminetests *****"
        npx jasmine
        
